### ISSUE TITLE
training/Makefile doesn't have a target for Negative.txt

### ISSUE THREAD

**Issue by danweflen** [jmtyszka/mrgaze#15]
The wiki says to use `make Negative.txt` to make the Negative.txt file, but the makefile in `training` has no `Negative.txt` target, and `make` has no implicit rules to make .txt files.

**Comment by jmtyszka** [comment]
Merged Thorlabs branch into Master. Should fix this and a lot of other bugs. May introduce new issues, so let me know.

**Comment by jmtyszka** [comment]
Merged Thorlabs branch into Master. Should fix this and a lot of other bugs. May introduce new issues, so let me know.
